export default {
    SET_DATA_PROGRESS: 'SET_DATA_PROGRESS',
    SET_DATA_PLAN: "SET_DATA_PLAN",
    SET_DATA_PROBLEM: 'SET_DATA_PROBLEM',
    SET_OKR: 'SET_OKR',
    SET_EDIT_SHOW: 'SET_EDIT_SHOW',
    // 设置用户时间
    SET_WEEKLYVO_EDIT:'SET_WEEKLYVO_EDIT'
};
